// MASTER
const SET_MASTER_MEMBERS_REDUCER = 'SET_MASTER_MEMBERS_REDUCER';

// ARISAN
const SET_ARISAN_MEMBERS_REDUCER = 'SET_ARISAN_MEMBERS_REDUCER';
const SET_ARISAN_MEETINGS_REDUCER = 'SET_ARISAN_MEETINGS_REDUCER';

// TRANSACTION
const SET_TRANSACTION_ARISAN_REDUCER = 'SET_TRANSACTION_ARISAN_REDUCER';

export {
  SET_MASTER_MEMBERS_REDUCER,
  SET_ARISAN_MEMBERS_REDUCER,
  SET_ARISAN_MEETINGS_REDUCER,
  SET_TRANSACTION_ARISAN_REDUCER,
};
