// MASTER
const SET_MASTER_MEMBERS_REDUCER = 'SET_MASTER_MEMBERS_REDUCER';

// ARISAN
const SET_ARISAN_MEMBERS_REDUCER = 'SET_ARISAN_MEMBERS_REDUCER';
const SET_ARISAN_SCHEDULES_REDUCER = 'SET_ARISAN_SCHEDULES_REDUCER';

export { SET_MASTER_MEMBERS_REDUCER, SET_ARISAN_MEMBERS_REDUCER, SET_ARISAN_SCHEDULES_REDUCER };
