const SET_DASHBOARD_USER_MANAGEMENT_GROUP_REDUCER = 'SET_DASHBOARD_USER_MANAGEMENT_GROUP_REDUCER';
const SET_DASHBOARD_USER_MANAGEMENT_USER_REDUCER = 'SET_DASHBOARD_USER_MANAGEMENT_USER_REDUCER';

const SET_DASHBOARD_PRODUCTS_REDUCER = 'SET_DASHBOARD_PRODUCTS_REDUCER';
const SET_DASHBOARD_BILLS_REDUCER = 'SET_DASHBOARD_BILLS_REDUCER';
const SET_DASHBOARD_BILL_TEMPLATES_REDUCER = 'SET_DASHBOARD_BILL_TEMPLATES_REDUCER';

const SET_DASHBOARD_FUND_WITHDRAWAL = 'SET_DASHBOARD_FUND_WITHDRAWAL';

const SET_DASHBOARD_SALDO_MUTATION_REPORTS_REDUCER = 'SET_DASHBOARD_SALDO_MUTATION_REPORTS_REDUCER';

const SET_SETTINGS_PROFILE_REDUCER = 'SET_SETTINGS_PROFILE_REDUCER';
const SET_SETTINGS_BANK_REDUCER = 'SET_SETTINGS_BANK_REDUCER';

export {
  SET_DASHBOARD_FUND_WITHDRAWAL,
  SET_SETTINGS_BANK_REDUCER,
  SET_SETTINGS_PROFILE_REDUCER,
  SET_DASHBOARD_SALDO_MUTATION_REPORTS_REDUCER,
  SET_DASHBOARD_BILLS_REDUCER,
  SET_DASHBOARD_PRODUCTS_REDUCER,
  SET_DASHBOARD_USER_MANAGEMENT_GROUP_REDUCER,
  SET_DASHBOARD_USER_MANAGEMENT_USER_REDUCER,
  SET_DASHBOARD_BILL_TEMPLATES_REDUCER,
};
